[package]
name = "paralllel_letter"
version = "0.1.0"
authors = ["franka911 <69419693+franka911@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "*"